apiVersion: v1
kind: Secret
metadata:
  name: filezen-secret
  namespace: default
  labels:
    app: filezen
type: Opaque
stringData:
  JWT_SECRET:             "filezen-jwt-k8s-super-secret-2024"
  CLOUDINARY_CLOUD_NAME:  "placeholder"
  CLOUDINARY_API_KEY:     "placeholder"
  CLOUDINARY_API_SECRET:  "placeholder"
  EMAIL_HOST:             "smtp.gmail.com"
  EMAIL_PORT:             "587"
  EMAIL_USER:             "placeholder@gmail.com"
  EMAIL_PASSWORD:         "placeholder"
  EMAIL_FROM:             "FileZen <placeholder@gmail.com>"
